### ISSUE TITLE
CI Tests failing with both python 2 and python 3

### ISSUE THREAD

**Issue by pi0** [nuxt-community/python-module#1]
Hey @icarito. I've tried make CI tests passing. But build fails with this error:

> ERROR in ./node_modules/py-loader?compiler=pj!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./test/fixture/pages/index.vue
    Module parse failed: Unexpected token (1:16)

https://circleci.com/gh/nuxt-community/python-module/4

Would you please take a look at it? (Since you are a python geek 🤓 )

**Comment by icarito** [comment]
Javascripthon is expected to only work for Python 3.5 -

**Comment by icarito** [comment]
I think I fixed circleci now. Thanks for the class on testing with Nuxtjs! :-D

**Comment by pi0** [comment]
Thanks for your amazing idea :) Science after public announcement many users will try this module, what's your idea to add instructions installing exactly python 3.5 and also adding fork of `metapensiero` to their *local* requirements.txt?

**Comment by icarito** [comment]
Before making an announcement :-) I'd like to work out the proper syntax with @azazel75 because we are still stabilizing the syntax for ES6 exports https://github.com/metapensiero/metapensiero.pj/issues/39 - hopefully we won't have to use a fork.

**Comment by pi0** [comment]
OK. So we will wait for a while before the announcement. Please ping me or @Atinux for that and good luck ;)

**Comment by Atinux** [comment]
This is awesome! I have no knowledge about Python, but when it's ready I would love to announce it publicly :)

**Comment by icarito** [comment]
@Atinux - I'm honored to contribute, a fan of Nuxt and Vue :-)
At this point the anonymous default exports have landed in the transpiler so things are working well.
Please review this and feel free to release it - hopefully it will be useful and improved upon.
Thanks in advance,

Sebastian

**Comment by azazel75** [comment]
@icarito I need to release it  ;-)

**Comment by pi0** [comment]
Initial version just released!

**Comment by azazel75** [comment]
wow !
